name: ManishPillewar
favicon: null
layout_spectrum: 0.25312
typography_spectrum: 0.35448
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.20435113133862615
  lightness: 0.2641073919367045
  saturation: 0.9402283043600619
  rhythmicContrast: 0.6417718045413494
purpose: []
